### PR TITLE
Fix Authbutton with long text  

### LINKED ISSUE #107: [Bug] Spotify friendlyName never shows up
Not a big bug but annoying nonetheless.

- Oneplus 7T
- Android 
- Europe
- 4G and Wifi (400Mbps)

Attached screenshots
lul

### PR DESCRIPTION
**Pull request by maxemiliang**
This should fix #107. 
Confirmed working on Oneplus 7T

Attaching screenshots of before and after.
Screenshot_20200426-200753
temp

### CODE REVIEW

File: app/components/Auth/components/Buttons/SocialAuthButton.js [hunk 1]
```diff
@@ -56,7 +56,8 @@ const styles = StyleSheet.create({
         backgroundColor: platform.color.primary,
     }),
     ButtonText: platform => ({
-        flexBasis: 140, // We set this so that it doesnt "cut out long text like spotify"
+        flexBasis: 150, // We set this so that it doesnt "cut out long text like spotify"
```
Comment (adilanchian) [inline app/components/Auth/components/Buttons/SocialAuthButton.js:59]: I think for this we should just use a minWidth instead of flexBasis. Seems like thats what the problem was. We will most likely run into this issue with AppleMusic as well haha.

Comment (maxemiliang) [reply app/components/Auth/components/Buttons/SocialAuthButton.js:59]: Yes, I think that would be better, will fix!

**Comment by isabellabrookes** [comment]
Oh, and don't forget to add yourself to the contributor's list in the readme.md if you want to flex your stuff :)

**Comment by adilanchian** [comment]
Looks awesome thanks for this!

**Comment by isabellabrookes** [comment]
@all-contributors please add @maxemiliang  for code
